PROMPT_TEXT = (
    'You will receive ONE product-promotion image. Return ONLY valid JSON with EXACTLY six keys in THIS order:\n'
    '{\n'
    '  "name": "<Polish name exactly as on image>",\n'
    '  "price": <number OR null>,\n'
    '  "promo": "<ONE of: NONE, SUP, DISC, DEALFIX, BXYG>",\n'
    '  "core": "<see grammar>",\n'
    '  "cond": "<see grammar>",\n'
    '  "nth": "<see grammar>"\n'
    '}\n\n'
    'Grammar (strict):\n'
    '• promo=NONE    → core="", cond="", nth=""\n'
    '• promo=SUP     → core="", cond="" OR N OR AxB OR alternatives like 1x12|2x6, nth=""\n'
    '• promo=DISC    → core=P (0..100), cond="" OR N ORclear AxB OR alternatives (e.g. 1x12|2x6),\n'
    '                  nth=""  OR  nth=N ONLY for phrases like "drugi/trzeci/N-ty … % taniej"\n'
    '• promo=DEALFIX → core="X.xx" (fixed price), cond=N OR AxB (e.g. "2" or "2x6"), nth=""\n'
    '• promo=BXYG    → core="X:Y" (e.g. "1:1","6:6"), cond="" OR N/AxB/alternatives, nth=""\n'
    'Notes:\n'
    '• cond values: use integers (N) or packs AxB; alternatives with "|". Omit cond when NO explicit condition.\n'
    '• Normalize cond: remove spaces, replace "×" or "X" with "x" (e.g., 2x6). Do not output q=1.\n'
    '• nth is used ONLY for DISC "… % taniej" on N-th item; otherwise nth="".\n\n'
    'Short rules for cond:\n'
    '• No real threshold → cond="" (do NOT output "1"), including phrases like "przy zakupie 1 szt.".\n'
    '• Use cond for packs like 1x12 or for real thresholds N>=2 (e.g., 2, 3, …).\n\n'
    'Keyword → promo (hard rules):\n'
    '• "<digit>+<digit>" OR "gratis" OR "w cenie" → BXYG, core="X:Y" (e.g., "6+6"→"6:6"). Ignore any % if this pattern exists.\n'
    '• "% taniej przy zakupie N" → DISC, core=P, cond=N, nth=""\n'
    '• "drugi/trzeci/N-ty … % taniej" → DISC, core=P, cond=N, nth=N\n'
    '• "drugi/N-ty za X zł" → DEALFIX, core="X.xx", cond=N, nth=""\n'
    '• "SUPERCENA" or "TERAZ TANIEJ" with NO percent → SUP (use cond only if an explicit condition is stated)\n'
    '• "NA STAŁE W OFERCIE" → NONE\n\n'
    'Price:\n'
    '• If no numeric price on the image → "price": null.\n'
    '• Use the discounted/new price if old+new are shown. Convert commas to dot (e.g., 5,33 → 5.33). No currency/% symbols.\n\n'
    'Other:\n'
    '• Keep the six keys exactly in the order above.\n'
    '• Types: name=string; price=number or null; promo=string; core=string; cond=string; nth=string.\n'
    '• core/cond/nth MUST be strings even if numeric (e.g., "52", "3", ""). No spaces allowed in core/cond/nth.\n'
    '• If multiple patterns match, priority: BXYG > DEALFIX > DISC > SUP > NONE.\n'
    '• Return JSON only — no extra text or backticks.'
)
