PROMPT_TEXT = (
    'You will receive ONE product-promotion image. Return ONLY valid JSON with EXACTLY four keys:\n'
    '{\n'
    '  "name": "<Polish name exactly as on image>",\n'
    '  "price": <number OR null>,\n'
    '  "promo": "<ONE of: NONE, SUP, DISC, DEALFIX, BXYG>",\n'
    '  "promo_args": "<see grammar>"\n'
    '}\n\n'
    'Grammar (strict):\n'
    '• NONE    → promo_args=""\n'
    '• SUP     → promo_args="" OR N                  (integer ≥1)\n'
    '• DISC    → promo_args= ONE of: P (0..100) | N | "N:P"  (e.g. 20 | 2 | "2:40")\n'
    '• DEALFIX → promo_args="N=price"                (e.g. "2=1.00")\n'
    '• BXYG    → promo_args="X:Y"                    (e.g. "1:1", "5:5")\n\n'
    'Keyword → promo (hard rules):\n'
    '• "X+Y gratis" → BXYG, promo_args="X:Y".\n'
    '• "drugi … % taniej" → DISC, promo_args="2:%".\n'
    '• "% taniej przy zakupie N" → DISC, "N:%".\n'
    '• "drugi za X zł" / "N-ty za X zł" → DEALFIX, "N=X".\n'
    ''
    '• "TERAZ TANIEJ" or standalone "X% TANIEJ" (no conditions) → DISC.\n'
    '• "TERAZ TANIEJ": if any “P% taniej”/“P% mniej” appears anywhere on the card → DISC.\n'
    '• "NA STAŁE W OFERCIE" → NONE.\n'
    '• "SUPERCENA" → SUP.\n\n'
    'Price:\n'
    '• If no numeric price on the image → "price": null.\n'
    '• Convert "5,33" or "5 33" to 5.33. If old+new are shown, use the discounted/new price.\n'
    '• Use dot for decimals; no currency/% symbols in numeric fields.\n\n'
    'Other:\n'
    '• Include pack size in "name" ONLY if that exact text is next to the product name.\n'
    '• If multiple patterns match, priority: BXYG > DEALFIX > DISC > SUP > NONE.\n'
    '• Return JSON only — no extra text or backticks.'
)


